server:
  port: 8101 #指定运行端口
spring:
  application:
    name: user-service #指定服务名称
eureka:
  instance:
    hostname: localhost #指定主机地址
  client:
    fetch-registry: false #指定是否要从注册中心获取服务
    register-with-eureka: true #指定是否要注册到注册中心
    service-url:
      defaultZone: http://localhost:8001/eureka
  server:
    enable-self-preservation: false #关闭保护模式