server:
  port: 10010 #指定运行端口
spring:
  application:
    name: gateway #指定服务名称
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: user-service
          uri: lb://userservice
          predicates:
            - Path=/user/**
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
logging:
  level:
    root: info
