server:
  port: 8201 #指定运行端口
  servlet:
    context-path: /orderservice
spring:
  application:
    name: order-service #指定服务名称
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
mybatis:
  mapper-locations: classpath:/mapper/*.xml
eureka:
  instance:
    hostname: localhost #指定主机地址
  client:
    fetch-registry: true #指定是否要从注册中心获取服务
    register-with-eureka: true #指定是否要注册到注册中心
    service-url:
      defaultZone: http://localhost:8001/eureka
  server:
    enable-self-preservation: false #关闭保护模式